FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive
RUN sed -i "s@http://.*archive.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN apt-get update && apt-get install -y wget git make
RUN wget -q \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh\
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

RUN exec bash \
    && . /root/.bashrc \
    && conda init bash \
    && conda activate \
    &&  conda install -c anaconda libstdcxx-ng

RUN  git clone https://github.com/TimDettmers/bitsandbytes && cd bitsandbytes &&  CUDA_VERSION=117 make cuda11x && CUDA_VERSION=117 python setup.py install

WORKDIR /app


CMD ["/bin/bash"]
